### ISSUE TITLE
Hi! Do you plan to release evaluation toolkit, training split and testing split (in Protocol II)?

### ISSUE THREAD

**Issue by 983632847** [bastech0/UTB180#1]

**Comment by BasitAlawode** [comment]
For the evaluation toolkit, any VOT evaluation toolkit such as pysot and pytracking can be utilized. The test videos are Videos 0111 to 0145 and Videos 0151 to 0165 (making a total of 50 videos). The rest are training videos. Thank you.

**Comment by 983632847** [comment]
Thank you
